name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libx11-xcb-dev \
            libxcb-xfixes0-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev

      - uses: Swatinem/rust-cache@v2

      - name: Install Main Toolchain
        run: rustup install nightly
      - run: rustup default nightly

      - name: Format
        run: cargo fmt --all --all-features --check

      - name: Clippy
        run: cargo clippy --all --all-features --all-targets

      - name: Test
        run: cargo test --all --all-features

      - name: Release
        run: cargo build --all-features --release

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: clipcatd
          path: target/release/clipcatd
      - uses: actions/upload-artifact@v3
        with:
          name: clipcatctl
          path: target/release/clipcatctl
      - uses: actions/upload-artifact@v3
        with:
          name: clipcat-menu
          path: target/release/clipcat-menu
      - uses: actions/upload-artifact@v3
        with:
          name: clipcat-notify
          path: target/release/clipcat-notify
