name: Build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{matrix.os}}

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
            libx11-xcb-dev \
            libxcb-xfixes0-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev

      - uses: Swatinem/rust-cache@v2

      - name: Install Main Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
          override: true

      - name: Format
        run: cargo fmt --all --check

      - name: Clippy
        run: cargo clippy --all

      - name: Test
        run: cargo test --all

      - name: Release
        run: cargo build --features=all --release

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: clipcatd
          path: target/release/clipcatd
      - uses: actions/upload-artifact@v3
        with:
          name: clipcatctl
          path: target/release/clipcatctl
      - uses: actions/upload-artifact@v3
        with:
          name: clipcat-menu
          path: target/release/clipcat-menu
      - uses: actions/upload-artifact@v3
        with:
          name: clipcat-notify
          path: target/release/clipcat-notify
