name: Build

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always
    RUSTFLAGS: "-D warnings"

jobs:
    all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  sudo apt-get update && \
                  sudo apt-get install -y \
                    libx11-xcb-dev \
                    libxcb-xfixes0-dev \
                    libxcb-render0-dev \
                    libxcb-shape0-dev \
                    protobuf-compiler

            - name: Install toolchain
              run: rustup install nightly --profile default
            - run: rustup default nightly

            - uses: Swatinem/rust-cache@v2

            - name: Format
              run: cargo fmt --all --check

            - name: Clippy X11
              run: cargo clippy --all --all-targets --features all-bins,x11

            - name: Clippy wayland
              run: cargo clippy --all --all-targets --features all-bins,wayland

            - name: Test X11
              run: cargo test --all --features all-bins,x11

            - name: Test wayland
              run: cargo test --all --features all-bins,wayland

            - name: Build X11
              run: cargo build --features all-bins,x11 --release

            - name: Upload X11 daemon
              uses: actions/upload-artifact@v3
              with:
                  name: clipcatd-x11
                  path: target/release/clipcatd
            - name: Upload X11 clipcat-notify
              uses: actions/upload-artifact@v3
              with:
                  name: clipcat-notify-x11
                  path: target/release/clipcat-notify

            - name: Build wayland
              run: cargo build --features all-bins,wayland --release

            - name: Upload wayland daemon
              uses: actions/upload-artifact@v3
              with:
                  name: clipcatd-wayland
                  path: target/release/clipcatd
            - uses: actions/upload-artifact@v3
              with:
                  name: clipcatctl
                  path: target/release/clipcatctl
            - uses: actions/upload-artifact@v3
              with:
                  name: clipcat-menu
                  path: target/release/clipcat-menu
            - name: Upload wayland clipcat-notify
              uses: actions/upload-artifact@v3
              with:
                  name: clipcat-notify-wayland
                  path: target/release/clipcat-notify
